using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
using System.Collections;

public class GoalTrigger : MonoBehaviour
{
    public GameObject virtualCamera;        // è™›æ“¬æ”å½±æ©Ÿï¼ˆè®“å®ƒåœä½ï¼‰
    public Text winText;                    // é¡¯ç¤º "ä½ è´äº†ï¼"
    public Text instructionText;            // é¡¯ç¤º "é»æ“Šä»»æ„éµå›ä¸»é¸å–®"
    public int Level = 0;
    private EatCoin eatCoin;
    private string interfaceSceneName = "Interface";  // ä¸»é¸å–® Scene åç¨±

    public bool isWon { get; private set; } = false;
    public bool hasWon { get; private set; } = false;

    private void OnTriggerEnter2D(Collider2D other)
    {
        if (other.CompareTag("Player"))
        {
            if (Level == 1)
            {
                eatCoin = other.transform.GetComponent<EatCoin>();
                if (eatCoin.remainingCoins != 0)
                {
                    return;
                }
            }
            Win();
        }
    }

    private void Update()
    {
        if (hasWon && Input.anyKeyDown)
        {
            SceneManager.LoadScene(interfaceSceneName);
        }
    }

    public void Win ()
    {
        isWon = true;

        GameObject cat = GameObject.FindGameObjectWithTag("Player");
        GameOverTrigger gameOverTrigger = cat.GetComponent<GameOverTrigger>();
        gameOverTrigger.isActive = false;

        virtualCamera.SetActive(false);

        winText.text = "ğŸ‰ You winï¼";


        GameObject[] policeList = GameObject.FindGameObjectsWithTag("BadGuy");

        foreach (GameObject police in policeList)
        {
            MonoBehaviour[] scripts = police.GetComponents<MonoBehaviour>();
            foreach (MonoBehaviour script in scripts)
            {
                script.enabled = false;
            }

            Rigidbody2D rb = police.GetComponent<Rigidbody2D>();
            if (rb != null)
            {
                rb.velocity = Vector2.zero;
                rb.isKinematic = true;
            }

            Animator animator = police.GetComponent<Animator>();
            if (animator != null)
            {
                animator.enabled = false;
            }
        }

        StartCoroutine(WaitToEnableExit());

        
    }

    private IEnumerator WaitToEnableExit()
    {
        yield return new WaitForSeconds(2f);
        hasWon = true;
        instructionText.text = "Press any key to return.";
    }
}